### ISSUE TITLE
Working with multiple animations ?

### ISSUE THREAD

**Issue by gnuletik** [bibixx/react-adobe-animate#1]
First, thanks for sharing this component !

I'd also like to know; did you succeed to make it work with multiple animations ?

**Comment by gnuletik** [comment]
Oh yes, it's working perfectly :)
The id of the animation have to be unique to each animation (take care when editing it, the id string is present twice ;))

Thanks again for this component ! :)

**Comment by bibixx** [comment]
Hey @gnuletik I'm glad that you made it to work but what do you mean by 
> the id string is present twice

?

**Comment by bibixx** [comment]
Ok, never mind I think I've got it

**Comment by gnuletik** [comment]
Sorry for the late answer.
I mean those two lines where the `id` is defined:
```
// library properties:
lib.properties = {
	id: 'ADEB108367EC924C8E19A8D3B7AA2AC3',
...
};
```

```
an.compositions = an.compositions || {};
an.compositions['ADEB108367EC924C8E19A8D3B7AA2AC3'] = {
...
}
```

**Comment by bibixx** [comment]
Yeah I figured it out. It is mentioned now in README
