### ISSUE TITLE
looking for a demo/ guide

### ISSUE THREAD

**Issue by gbarakat** [bibixx/react-adobe-animate#10]
Hi Bartosz,

Thanks for working on this component, sounds promising.

I am looking for a demo or guide to help me to use this component. I have tried to clone it but it doesn't work. so can you help me out?

**Comment by bibixx** [comment]
Hey, sorry for late response, but I didn't have much time. You can see the example app that I have created on branch [gh-pages](https://github.com/bibixx/react-adobe-animate/tree/gh-pages). It implements two animations with ability to pause it. If you have any questions about it, let me know and I'll try to respond as fast as possible

**Comment by bibixx** [comment]
@gbarakat did you find the way to implement it? If not let me know. Otherwise please close this issue

**Comment by bibixx** [comment]
Oh and by the way I have just updated the README with the live example on codesandbox: https://github.com/bibixx/react-adobe-animate#examples

**Comment by bibixx** [comment]
Closing due to the lack of response. If you still have a problem feel free to reopen this issue
