### ISSUE TITLE
Animation with images not showing

### ISSUE THREAD

**Issue by CoetzeeStrydom** [bibixx/react-adobe-animate#11]
Hi, I have an exported animation that pulls various images to use in the animation. The canvas gets created and no errors are displayed but also canvas is empty. Have tried this with a sprite as well.

**Comment by dane-brown** [comment]
Any update on this @bibixx ?

**Comment by bibixx** [comment]
Unfortunately not. I didn't have time recently. But tomorrow I'll try to finally take care of this project 😄

**Comment by dane-brown** [comment]
Awesome, thanks for the update

**Comment by bibixx** [comment]
Hey @dane-brown @CoetzeeStrydom please try using the `@next` version of the package and let me know if the animation works

**Comment by dane-brown** [comment]
Thanks will give it a try

**Comment by bibixx** [comment]
@dane-brown any updates?
