### ISSUE TITLE
v2.2.0 removes getAnimationObject call

### ISSUE THREAD

**Issue by gnuletik** [bibixx/react-adobe-animate#16]
Hi,

It seems that the version 2.2.0 removes the `getAnimationObject` call on init : https://github.com/bibixx/react-adobe-animate/commit/90c389214288bef34bd58b5d8608405357468afc

This props is important as it allows to access the createJs instance in order to handle the `loop`, `visible` and `onComplete` callback.
Is it possible to reintroduce it ?

Thanks

**Comment by bibixx** [comment]
Oh. Really? Sure thing. I have in mind doing some work on this package (some refactoring + tests). I am bringing it back as we speak 🙂

**Comment by gnuletik** [comment]
Nice ! Thanks for the fast answer :)

**Comment by gnuletik** [comment]
Awesome ! Thanks :)
