### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by gnuletik** [bibixx/react-adobe-animate#17]
It would be nice to add Typescript support.

**Comment by bibixx** [comment]
Have it in my todo list 😄. But the fact that this package has to dig so deep into the adobe's code scares the hell out of me

**Comment by gnuletik** [comment]
Awesome ! I guess that the CreateJS call can be ignored by Typescript. The real value may be to export Component's types in order to integrate it in Typescript codebase.


Thanks @bibixx ! :)

**Comment by bibixx** [comment]
Yeah it definitely can
