### ISSUE TITLE
Mouseover not detected

### ISSUE THREAD

**Issue by dane-brown** [bibixx/react-adobe-animate#23]
Currently, we use a mouseover event to reveal certain elements of a game although the mouseover events within the animation aren't being detected. Any ideas on how to fix this?

`stage.mc_pipes.mc_chosen_ball_1.addEventListener('mouseover', reveal_chosen_1);`

**Comment by bibixx** [comment]
I'll try to take a look at it today 😄

**Comment by dane-brown** [comment]
Thanks man :)

**Comment by bibixx** [comment]
Hey, sorry I didn't respond yet, but I am really short on time recently, I'll hope to look at it tomorrow after work

**Comment by dane-brown** [comment]
No worries, whenever you can get to it

**Comment by dane-brown** [comment]
Hey @bibixx any luck here?
