### ISSUE TITLE
How do I control the animation?

### ISSUE THREAD

**Issue by axeen** [bibixx/react-adobe-animate#27]
So the animation is working as it should, and I can control if it's paused or not, but what if I want to play it again? There are functions called .seek(), .pause(), .stop(), etc. in the export itself, but I couldn't really access them in a straightforward manner, and when I did get a hold of them they weren't working due to them having the wrong scope.

Is there an easy way to control the timeline of the animation? All I want to do really is to reset the animation so that I can play it again.

**Comment by bibixx** [comment]
Hi, I know that this comment was left a long time ago, but I didn't have much time to do OSS.
It may not be needed anymore but I will answer this question as it may be useful for others in the future.

So to access the `play`, `stop` or `seek` functions that are defined in the animation export you have to access the animationObject using (`getAnimationObject` prop on the component). Then the `animationObject.stage.play()`, `animationObject.stage.stop()`, `animationObject.stage.seek()` functions should be available.

Also to make the animation play again you should set the `paused` prop back to `false`

If you or anyone else in the future needs any more explanation feel free to reopen this issue

**Comment by axeen** [comment]
Yes, I was able to figure this out eventually, but I'm still grateful you took the time to reply! As you said, It'll be very useful for others with the same problem who find this.
