### ISSUE TITLE
TypeError: Cannot read property 'getLibrary' of undefined

### ISSUE THREAD

**Issue by ekfuhrmann** [bibixx/react-adobe-animate#3]
When trying to use the example you provided, I receive the following error:
`TypeError: Cannot read property 'getLibrary' of undefined`

My `index.html` is as follows:
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>App</title>
</head>

<body>
    <div id="root"></div>
    <script src="https://code.createjs.com/createjs-2015.11.26.min.js" type="text/javascript"></script>
    <script src="./lishtml5.js"></script>
</body>

</html>
```

`getLibrary` reference is found within the Adobe Animate output inside of `lishtml5.js`

**Comment by bibixx** [comment]
So you get this error when using exactly this?
https://github.com/bibixx/react-adobe-animate/tree/gh-pages

**Comment by bibixx** [comment]
Ok and what `animationName` prop are you passing?

**Comment by bibixx** [comment]
Because you should pass `lishtml5` for this particular animation

**Comment by ekfuhrmann** [comment]
Sorry for the delay in responding, I was out yesterday.

I ran the following:

```js 
<AnimateCC animationName="lishtml5" />
```

I tried this with a different Animate.js file as well (updating the name and all) and got a slightly different error but similar premise. It seems like I'm running into issues with certain functions coming out of Animate being defined.

**Comment by ekfuhrmann** [comment]
I'm pretty terrible at explaining the issue, so I created a new CRA example with the issue I'm getting.

Check it out [here](https://github.com/ekfuhrmann/react-adobe-animate-example).

**Comment by bibixx** [comment]
And do you realise that this `approachOne.js` file has inside this mine `lishtml5.js` animation?

**Comment by ekfuhrmann** [comment]
Ugh, so sorry. In my rush to throw together this example repo, I forgot that at some point in my other project I renamed your `lishtml5.js` animation.

I've now updated the animation to the correct file. (really sorry for wasting your time with that)!

The animation I'm trying to serve is the same as the one we currently first use on [this](https://braveux.com/approach) page. This site is of course not built with react, but it does serve as the idea behind the react implementation I was working on.

**Comment by bibixx** [comment]
So it seems that, as you mentioned previously, all of this is caused by the fact that it was created some time ago and the Animate's API changed a bit. But fortunately I managed to get it working!

So first of all name of the animation is scene1animationv2 (You can find it after this comment `// stage content:` in your animation file (Btw I have already added it to README).

Secondly to make it work you have to add
```javascript
(lib.Stage = function (canvas) {
      createjs.Stage.call(this, canvas);
    }).prototype = p = new createjs.Stage();

    an.bootcompsLoaded = an.bootcompsLoaded || [];

    if(!an.bootstrapListeners) {
      an.bootstrapListeners = [];
    }

    an.bootstrapCallback = function (fnCallback) {
      an.bootstrapListeners.push(fnCallback);
      if (an.bootcompsLoaded.length > 0) {
        for (var i = 0; i < an.bootcompsLoaded.length; ++i) {
          fnCallback(an.bootcompsLoaded[i]);
        }
      }
    };

    an.compositions = an.compositions || {};
    an.compositions['qpka'] = { // <- you can set this id on your own. Just make sure to have it unique for every animation
      getStage: function () { return exportRoot.getStage(); },
      getLibrary: function () { return lib; },
      getSpriteSheet: function () { return ss; },
      getImages: function () { return img; }
    };

    an.compositionLoaded = function (id) {
      an.bootcompsLoaded.push(id);
      for (var j = 0; j < an.bootstrapListeners.length; j++) {
        an.bootstrapListeners[j](id);
      }
    }

    an.getComposition = function (id) {
      return an.compositions[id];
    }
```

Just before
```javascript
})(
  (libOne = libOne || {}),
  (images = images || {}),
  (createjs = createjs || {}),
  (ss = ss || {}),
  (AdobeAn = AdobeAn || {})
);
var libOne, images, createjs, ss, AdobeAn;
```

Oh and also you can upgrade the package to 2.1.0

**Comment by ekfuhrmann** [comment]
This is awesome, those changes did indeed get it working.

Thank you so much for helping out with that. I think it's great what you're doing with this component. I was so excited when I came across it as it just makes canvas animations that much easier to work with in React.

I'll have to at some point update my Animate projects as well, but I can't begin to thank you enough for not only figuring out the issue but helping get it working again.

**Comment by bibixx** [comment]
No worries. I'm happy that I could help
