### ISSUE TITLE
null is not an object (evaluating 't.setTransform') on iOS Safari

### ISSUE THREAD

**Issue by gnuletik** [bibixx/react-adobe-animate#36]
We recently ported a project using this library on mobile web browsers.
This library works as expected on every mobile browsers we tested except on iPhone 6S Safari (iOS 13.5.1).
Other versions of iOS are not tested.

On iOS Safari, at some random times (happens usually after 5-10 minutes of loading and unloading animations), we are experiencing the following error : `null is not an object (evaluating 't.setTransform')`
This error is thrown in the animations generated by Adobe Animate inside the `startAnimation` function called from `react-adobe-animate`.

Does someone already faces similar issues ?

**Comment by kiuKisas** [comment]
![2020-12-06_15-34_1](https://user-images.githubusercontent.com/12698940/101347355-40477800-388a-11eb-811d-0aa2b57cf1a0.png)
![2020-12-06_15-34](https://user-images.githubusercontent.com/12698940/101347360-4178a500-388a-11eb-8acb-2c6ff3ffb7a5.png)

**Comment by kiuKisas** [comment]
![2020-12-09_15-00](https://user-images.githubusercontent.com/12698940/101640789-3ca22580-3a31-11eb-9f75-2784d4d9cc83.png)
