### ISSUE TITLE
getContext undefined (Canvas is null)

### ISSUE THREAD

**Issue by gregcoffman** [bibixx/react-adobe-animate#41]
I'm fairly new to react/jsx, so I apologize if this is not a bug.  I'm unclear if the order in execution could be the problem. Version 2.3.1.   Cheers.

index.js:
![image](https://user-images.githubusercontent.com/15002202/104128964-6a340480-5338-11eb-8598-0cc442019fdb.png)

CanvasHero.js Component:
![image](https://user-images.githubusercontent.com/15002202/104129002-9780b280-5338-11eb-8513-2351061094a7.png)

Canvas.tsx
![image](https://user-images.githubusercontent.com/15002202/104129073-03631b00-5339-11eb-9f9b-4e4bf956408e.png)

Canvas appears to be null
![image](https://user-images.githubusercontent.com/15002202/104129088-183fae80-5339-11eb-8587-0e5929b57169.png)

Much appreciated!

**Comment by bibixx** [comment]
@gregcoffman 🤔 everything seems to be looking fine (I can see that it is almost an unchanged code from my example). I'm not really sure what is the issue, however I'd suspect that here is something wrong with the Adobe Animate export. Could you create a repo/sandbox/send the animation itself? (If you don't want to post it publicly you can create a private repo and add me to it or send me the animation directly via email (js file only) to bartosz+a.github@legiec.io)

**Comment by gregcoffman** [comment]
Thanks! I just pushed the js file to private repo.

**Comment by bibixx** [comment]
@gregcoffman Okay, I know what the issue is. You didn't copy the folder with images. Copy the `images/Canvas.png` folder to the `public` folder in Create React App and the animation should work.

I'll try to dig more into the issue and try to include a check for it. If the image is not found I could potentially throw a nicer error in the console.

**Comment by gregcoffman** [comment]
That was it!  Very much appreciate the quick assist 🥇 👍

**Comment by bibixx** [comment]
@gregcoffman FYI in `2.4.0` I have added a more human-readable error to help people in the future
