### ISSUE TITLE
Event Listeners

### ISSUE THREAD

**Issue by Neobii** [bibixx/react-adobe-animate#43]
Hi, I'm [trying to use](https://github.com/Shielkwamm/shielkwamm/tree/master/components) some animate stuff inside react as well.

I'm wondering if you have an easier way to handle which animations are playing and having callbacks on certain frames bubble up to the react components.

I am also using [zimjs](https://zimjs.com/)

**Comment by bibixx** [comment]
@Neobii I would assume that it could help.
When you render the animation using this component you can have access to the exact internal object that Animate uses. And using that you can listen on different events that it emits (I'm not really sure as I don't use Animate daily but this docs could be helpful https://www.createjs.com/docs/easeljs/modules/EaselJS.html)

```tsx
import AnimateCC from "react-adobe-animate";

const App = () => {
  const setAnimationObject = (obj) => {
    obj.addEventListener('yourEvent', console.log)
  }

  return (
    <AnimateCC
      animationName="yourAnimationName"
      getAnimationObject={setAnimationObject}
    />
  );
};
```

**Comment by bibixx** [comment]
However I can see that you are using next.js. I am not sure but it could be tricky to setup it with next.js because of the SSR

**Comment by Neobii** [comment]
Okay, good to know, I'll try it out here in a lil bit.  My biggest use case is so far is managing state in react and animation without doing rerenders and avoiding race conditions or making sure all animations are complete.  For this kind of work, do you think using events is okay or do you think using the new async/await is better than using event listeners?

**Comment by Neobii** [comment]
Okay, I see that you are using `componentWillMount`.  The thing that helps me get by with SSR is the `useEffect` react hook... this fixes the window is undefined issue when building the pages.

**Comment by bibixx** [comment]
@Neobii the `componentDidMount` wasn't really an issue, but the fact that I was referencing `window` object. I have pushed a change that should add SSR support (#44, I have also added an example how to use it with Next.js).

As to the async/await vs listeners to be honest I'm not really sure as to what do you mean. I couldn't figure out how does your code work as I am not familiar at all with zimjs and as so I don't really see where you'd like to change it. If you could provide me with an example code using react-adobe-animate, then I could probably help you a bit (codesandbox example would be the best)
