### ISSUE TITLE
Can you please help it working with CurriculumAssociates/createjs-accessibility

### ISSUE THREAD

**Issue by engrsandeep** [bibixx/react-adobe-animate#50]
Hi @witcher112 @gnuletik @bibixx 

We need to add accessibility, Can you please to implement.
https://github.com/CurriculumAssociates/createjs-accessibility

Many Thanks.

**Comment by gnuletik** [comment]
Hi @engrsandeep,

I don't know this project.
From the project's README, it seems that this dependency requires editing the animation generated by adobe animate.

During :
- initialization: call `AccessibilityModule.register`
- update: call `stage.accessibilityTranslator.update`

You may parse and replace the generated animation file to reach this but I think this is out of this `react-adobe-animate` scope.

With the fixed animation file, `react-adobe-animate` may call `AccessibilityModule.resize`.

If you have another idea to implement it, feel free to submit a PR.

**Comment by engrsandeep** [comment]
Thanks for quick reply. @gnuletik 

Issue is **getAnimationObject** do not expose stage, it only expose root element like **exportRoot** (when export from AnimateCC).  Can you allow to get stage object, that will be helpful in implementing  accessibility.

Regards,
Sandeep

**Comment by bibixx** [comment]
@engrsandeep the object that is passed as an argument to the `getAnimationObject` function should have a `.stage` property that is a reference to the stage that the element has been added to (it also has `getStage` which is apparently deprecated)

```tsx
import * as React from "react";
import { useState } from "react";
import AnimateCC, { GetAnimationObjectParameter } from "react-adobe-animate";

const App = () => {
  const [animationObject, getAnimationObject] = useState<GetAnimationObjectParameter|null>(null);

  console.log(animationObject?.stage);

  return (
    <AnimateCC
      animationName="lishtml5"
      getAnimationObject={getAnimationObject}
    />
  );
};

export default App;
```

**Comment by bibixx** [comment]
However I can see that it may not be populated from the very beginning as I think we call `getAnimationObject` **before** the stage has been created. I'll try to take a look at it and figure out if we can do it **after**

**Comment by engrsandeep** [comment]
Thanks @bibixx.

**Comment by engrsandeep** [comment]
@bibixx  stage is private member thats why i think it is not available as well.

**Comment by engrsandeep** [comment]
@bibixx is there way to load animate file dynamically.

**Comment by bibixx** [comment]
Unfortunately there is no way of loading the animations dynamically. Closing this issue as there seems there is not much I can do here. @engrsandeep If you feel there is something that can be done here, feel free to reopen this issue
