### ISSUE TITLE
when animationName is changed, the referenced animation doesn't load

### ISSUE THREAD

**Issue by Neobii** [bibixx/react-adobe-animate#51]
When animationName is changed, the new animation doesn't load.

```jsx
function playback({ state }){
  return (
	  <AnimateCC
	    animationName={state.playback.actor}
	    getAnimationObject={getAnimationObject}
	  /> 
  );
}
```

Perhaps it would be easiest if I just always load different animate into different AnimateCC components?

**Comment by bibixx** [comment]
🤔 the easiest fix for this issue for now would be to add a `key` prop to the `AnimateCC` component to force the full rerender to make sure everything is being setup alright 

```jsx
function playback({ state })(
  <AnimateCC
    key={state.playback.actor}
    animationName={state.playback.actor}
    getAnimationObject={getAnimationObject}
  /> 
)
```
