### ISSUE TITLE
Error when using Javascript instead of type script

### ISSUE THREAD

**Issue by havokentity** [bibixx/react-adobe-animate#53]
I get this error 'GetAnimationObjectParameter' is not exported from 'react-adobe-animate'. when I try to use javascript files instead of typescript. Is it mandatory that we only use typescript?

**Comment by bibixx** [comment]
@havokentity could you provide me a code sample? Most probably when using JS you should simply not import it.

```jsx
import { useState } from "react";
import AnimateCC from "react-adobe-animate";

const App = () => {
  const [paused, setPaused] = useState(true);
  const [animationObject, getAnimationObject] = useState(null);
  const onClick = () => setPaused(!paused);

  console.log(animationObject);

  return (
    <div style={{ width: "400px" }}>
      <AnimateCC
        animationName="lishtml5"
        getAnimationObject={getAnimationObject}
        paused={paused}
      />

      <AnimateCC
        animationName="lishtml5"
        composition="C1475B64B160904BB90B34246A5FF54B"
        paused={paused}
      />

      <button onClick={onClick}>{paused ? "Unpause" : "Pause"}</button><br />
    </div>
  );
};
```

**Comment by bibixx** [comment]
@havokentity please let me know if the solution I have provided helped

**Comment by havokentity** [comment]
oh my goodness this worked!! I'm new to JS/TypeScript, did you just remove the _type_ associated with _useState_ is all? btw thanks a ton!

**Comment by bibixx** [comment]
Yup, if you want to use JS instead of TS you just have to strip the code from type definitions. You were getting the error `'GetAnimationObjectParameter' is not exported from 'react-adobe-animate'` because `GetAnimationObjectParameter` is a type, which JS has no way to understand
