### ISSUE TITLE
AnimateCC: AdobeAn dependency not found

### ISSUE THREAD

**Issue by OkuruchiDan** [bibixx/react-adobe-animate#69]
## Introduction
Hello there! Let's talk about what we had found :) _We will be glad if you will have time to take a look on our issue!_
We are using `Next.js` for our landing page, and we DO NOT use any `typescript` or any `types`, if it's important.
We have 2 Adobe animation with static `.js` files for them on our server.
We had go through your examples but we stacked on one unusual workflow.

## How to reproduce a bug
Firstly we have a landing page with 2 animations. Now all working is fine. When you look at it and when you go somewhere and return, no error are throned. Instead of one case when you go to some page and you click refresh button and then go back to page with animation you will see the error about `AnimateCC: AdobeAn dependency not found`. 
We had try to solve this problem with `next/script` optimisation. We had combined: placing the script on different levels of app, different loading strategies, static and dynamic imports and etc.. But nothing working with us.

### Step by step reproducing on stage
1. Go to [Staging landing page](https://staging.perfsol.tech/ ).
2. Go to any other page, for example [Blog page](https://staging.perfsol.tech/blog) or one of [Case-studies](https://staging.perfsol.tech/case-studies/3-twinbody).
3. Refresh the page(using refresh button or hot keys, no matter).
4. Click on back button in your browser(should redirect you to '/' landing page). 
5. Tada!!! you have an **_Error_** :)
6. Open console to see the logs of your library.

### Ideas 
Probably this issue is relative to SSR(server side rendering) of our `Next.js` app.
Also looks like the scripts haven't enough  time for loading, so maybe you need to add some checking methods
Will be very cool of you will provide some `onError` method to handle runtime errors.

_Thanks for reading, wish you the best!_

**Comment by bibixx** [comment]
@OkuruchiDan I have stared working on rebuilding the whole package to use react hooks, so that it works better with Next.js (and to fix some other issues, like #51)

However for now — reproduction steps: https://codesandbox.io/s/react-adobe-animate-next-js-routing-issue-od2ky

**Comment by OkuruchiDan** [comment]
@bibixx Hello! Thanks for your answer! I can show you haw I had solved this problem on my project, of course this solution not so solid as can be given from your side (I'm using session storage for keep a flag about scripts loading), but it works, so can be like a temporary solution)

**Comment by OkuruchiDan** [comment]
@bibixx Hello again! I have soled this issue with adding flag about script loading to local storage. 
So now I display my animation only after all Scripts(create.js, scripts of animation) are loaded.

**Comment by bibixx** [comment]
I know it was some time 😅 But if anybody encounters the same issue in the future please take a look at the updated example for [Next.js](https://github.com/bibixx/react-adobe-animate/blob/main/examples/next/pages/index.tsx) that should allow you to render the animation after the scripts has loaded
